env:
  browser: true
  es2021: true
extends: ["airbnb-base", "plugin:prettier/recommended"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-await-in-loop:
    - warn
  radix:
    - error
    - as-needed
  default-param-last:
    - warn
  no-underscore-dangle: "off"
  no-param-reassign:
    - warn
  class-methods-use-this:
    - warn
  no-unused-vars:
    - warn
  no-nested-ternary: "off"
  no-restricted-syntax:
    - warn
    - selector: ForInStatement
      message:
        for..in loops iterate over the entire prototype chain, which is virtually
        never what you want. Use Object.{keys,values,entries}, and iterate over the
        resulting array.
    - selector: LabeledStatement
      message:
        Labels are a form of GOTO; using them makes code confusing and hard to
        maintain and understand.
    - selector: WithStatement
      message:
        "`with` is disallowed in strict mode because it makes code impossible
        to predict and optimize."
  import/extensions:
    - warn
    - always
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
globals:
  GameCanvas: readonly
  add: readonly
  make: readonly
  readd: readonly
  get: readonly
  destroy: readonly
  destroyAll: readonly
  pos: readonly
  scale: readonly
  rotate: readonly
  color: readonly
  opacity: readonly
  sprite: readonly
  text: readonly
  rect: readonly
  circle: readonly
  uvquad: readonly
  area: readonly
  anchor: readonly
  z: readonly
  outline: readonly
  body: readonly
  doubleJump: readonly
  move: readonly
  offscreen: readonly
  follow: readonly
  shader: readonly
  timer: readonly
  fixed: readonly
  stay: readonly
  health: readonly
  lifespan: readonly
  state: readonly
  fadeIn: readonly
  mask: readonly
  drawon: readonly
  tile: readonly
  agent: readonly
  on: readonly
  onUpdate: readonly
  onDraw: readonly
  onAdd: readonly
  onDestroy: readonly
  onLoad: readonly
  onLoading: readonly
  onError: readonly
  onResize: readonly
  onCleanup: readonly
  onGamepadConnect: readonly
  onGamepadDisconnect: readonly
  onCollide: readonly
  onCollideUpdate: readonly
  onCollideEnd: readonly
  onClick: readonly
  onHover: readonly
  onHoverUpdate: readonly
  onHoverEnd: readonly
  onKeyDown: readonly
  onKeyPress: readonly
  onKeyPressRepeat: readonly
  onKeyRelease: readonly
  onCharInput: readonly
  onMouseDown: readonly
  onMousePress: readonly
  onMouseRelease: readonly
  onMouseMove: readonly
  onTouchStart: readonly
  onTouchMove: readonly
  onTouchEnd: readonly
  onScroll: readonly
  onHide: readonly
  onShow: readonly
  onGamepadButtonDown: readonly
  onGamepadButtonPress: readonly
  onGamepadButtonRelease: readonly
  onGamepadStick: readonly
  onSceneLeave: readonly
  loadRoot: readonly
  loadSprite: readonly
  loadSpriteAtlas: readonly
  loadAseprite: readonly
  loadPedit: readonly
  loadBean: readonly
  loadJSON: readonly
  loadSound: readonly
  loadFont: readonly
  loadBitmapFont: readonly
  loadShader: readonly
  loadShaderURL: readonly
  load: readonly
  loadProgress: readonly
  getSprite: readonly
  getSound: readonly
  getFont: readonly
  getBitmapFont: readonly
  getShader: readonly
  getAsset: readonly
  SpriteData: readonly
  SoundData: readonly
  width: readonly
  height: readonly
  center: readonly
  dt: readonly
  time: readonly
  isFocused: readonly
  isTouchscreen: readonly
  mousePos: readonly
  mouseDeltaPos: readonly
  isKeyDown: readonly
  isKeyPressed: readonly
  isKeyPressedRepeat: readonly
  isKeyReleased: readonly
  isMouseDown: readonly
  isMousePressed: readonly
  isMouseReleased: readonly
  isMouseMoved: readonly
  isGamepadButtonPressed: readonly
  isGamepadButtonDown: readonly
  isGamepadButtonReleased: readonly
  getGamepadStick: readonly
  charInputted: readonly
  shake: readonly
  camPos: readonly
  camScale: readonly
  camRot: readonly
  toScreen: readonly
  toWorld: readonly
  setGravity: readonly
  getGravity: readonly
  setBackground: readonly
  getBackground: readonly
  getGamepads: readonly
  setCursor: readonly
  getCursor: readonly
  setCursorLocked: readonly
  isCursorLocked: readonly
  setFullscreen: readonly
  isFullscreen: readonly
  wait: readonly
  loop: readonly
  play: readonly
  burp: readonly
  volume: readonly
  audioCtx: readonly
  rand: readonly
  randi: readonly
  randSeed: readonly
  vec2: readonly
  rgb: readonly
  hsl2rgb: readonly
  quad: readonly
  choose: readonly
  chance: readonly
  lerp: readonly
  tween: readonly
  easings: readonly
  map: readonly
  mapc: readonly
  wave: readonly
  deg2rad: readonly
  rad2deg: readonly
  clamp: readonly
  testLinePoint: readonly
  testLineLine: readonly
  testLineCircle: readonly
  testRectRect: readonly
  testRectLine: readonly
  testRectPoint: readonly
  testCirclePolygon: readonly
  Line: readonly
  Rect: readonly
  Circle: readonly
  Polygon: readonly
  Vec2: readonly
  Color: readonly
  Mat4: readonly
  Quad: readonly
  RNG: readonly
  scene: readonly
  go: readonly
  addLevel: readonly
  getData: readonly
  setData: readonly
  drawSprite: readonly
  drawText: readonly
  drawRect: readonly
  drawLine: readonly
  drawLines: readonly
  drawTriangle: readonly
  drawCircle: readonly
  drawEllipse: readonly
  drawPolygon: readonly
  drawUVQuad: readonly
  drawFormattedText: readonly
  drawMasked: readonly
  drawSubtracted: readonly
  pushTransform: readonly
  popTransform: readonly
  pushTranslate: readonly
  pushScale: readonly
  pushRotate: readonly
  pushMatrix: readonly
  usePostEffect: readonly
  formatText: readonly
  makeCanvas: readonly
  debug: readonly
  plug: readonly
  screenshot: readonly
  download: readonly
  downloadText: readonly
  downloadJSON: readonly
  downloadBlob: readonly
  record: readonly
  addKaboom: readonly
  ASCII_CHARS: readonly
  LEFT: readonly
  RIGHT: readonly
  UP: readonly
  DOWN: readonly
  RED: readonly
  GREEN: readonly
  BLUE: readonly
  YELLOW: readonly
  MAGENTA: readonly
  CYAN: readonly
  WHITE: readonly
  BLACK: readonly
  canvas: readonly
  quit: readonly
  Event: readonly
  EventHandler: readonly
  EventController: readonly
  VERSION: readonly
settings:
  import/extensions:
    - ".js"
